
GCC = g++ -std=c++11
RM = rm

UI: UIerror.o UserInterface.o UImain.o
	$(GCC) UIerror.o UserInterface.o UImain.o -o UI

UIerror.o: UIerror.cc UIerror.h
	$(GCC) -c UIerror.cc

UserInterface.o: UserInterface.h UserInterface.cc
	$(GCC) -c UserInterface.cc

UImain.o: UImain.cc
	$(GCC) -c UImain.cc

clean:
	$(RM) UIerror.o UserInterface.o UImain.o UI
