
GCC = g++
RM = rm

UI: ErrorClass.o UserInterface.o UImain.o
	$(GCC) ErrorClass.o UserInterface.o UImain.o -o UI

ErrorClass.o: ErrorClass.cc ErrorClass.h
	$(GCC) -c ErrorClass.cc

UserInterface.o: UserInterface.h UserInterface.cc
	$(GCC) -c UserInterface.cc

UImain.o: UImain.cc
	$(GCC) -c UImain.cc

clean:
	$(RM) ErrorClass.o UserInterface.o UImain.o UI
